### ISSUE TITLE
Use Catmandu::Fix::Base, deprecate Catmandu::MARC::Fix::Inline::*

### ISSUE THREAD

**Issue by nichtich** [LibreCat/Catmandu-MARC#27]
I don't know since when, but inline fixes are possible in Catmandu, if a fix is derived from Catmandu::Fix::Base (which Catmandu::MARC::Fix::* are not yet).

**Comment by phochste** [comment]
Catmandu::Fix::Base  is only supported in Fixes that do 'emit'. Catmandu::MARC contains some non-emit fixes. I think this is an issue that should be solved in Catmandu::Fix::Base  first.

**Comment by phochste** [comment]
Fixed in the dev branch. But Catmandu::MARC::Fix::Inline still has its use. All catmandu fixes normally change data inline. You would need to add a special construct to extract data

   use Catmandu::Fix::marc_map as => 'marc_map';

   my $result = marc_map($data, '245a','my_field')->{my_field);

In the Catmandu::MARC::Fix::Inline::marc_map you could say:

   my $result = marc_map($data,'245a');
